// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwsngmhgjayjfwfilpgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3c25nbWhnamF5amZ3ZmlscGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjYyOTYsImV4cCI6MjA3MTEwMjI5Nn0.670kZYTLldjaDkqFuH49Pou4r6mBfvLwzSuSnojF29g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      // Remove `storage: localStorage`
    }
  }
);
